
[general]

host=glcfapp07.umd.edu
# host=localhost
# host=192.168.75.128
port=8080

nodata_file=%(root)s/conf/nodata.png
# web_path=h:\mfeng\test\glcf\fcc_1975\test\map\release
map_path=%(root)s/map
web_path=%(root)s/web
test_path=%(root)s/test
# web_path=h:\mfeng\test\glcf\fcc_1975\test\map\map
# web_path=h:\mfeng\test\glcf\fcc_1975\test\map\map

# dmap=ssh glcfpro19.umd.edu "python /data/glcf-st-004/data/workspace/fengm/serv/build_map_tile.py -t %[tag]s -l %[level]s -c %[col]s -r %[row]s " &
dmap=python /data/glcf-st-004/data/workspace/fengm/serv/build_map_tile.py -t %[tag]s -l %[level]s -c %[col]s -r %[row]s

[conf]
output=/data/glcf-st-004/data/workspace/fengm/serv/map

# aggregate=mean
# aggregate=dominated
# aggregate=dominated
aggregate=mean
# mmu=true
mmu=false
log=/export2/data/mfeng/map_server.log
temp=/export2/data/mfeng/tmp/build

[forest_loss_2010_2015_v03]
file=/data/glcf-nx-002/data/PALSAR/fcc/fcc_01/list/fcc_2010_2015_30p.shp
percent=19

[forest_loss_2014_2015_v01]
file=/data/glcf-nx-002/data/PALSAR/fcc/fcc_01/list/fcc_2014_2015_30p.shp
percent=19

[forest_gain_2010_2015_v04]
file=/data/glcf-nx-002/data/PALSAR/fcc/fcc_01/list/fcc_2010_2015_30p.shp
percent=91

[forest_gain_2014_2015_v01]
file=/data/glcf-nx-002/data/PALSAR/fcc/fcc_01/list/fcc_2014_2015_30p.shp
percent=91

[tcc_global_2015_v03]
file=/data/glcf-nx-003/fengm/tcc/global/v05/comp/2015/comp_etm_oli/list/tcc_global_2015.shp

[tcc_global_2010_v03]
file=/data/glcf-st-002/fengm-2/fcc/global_tcc_2010_comp.shp

[water_freq_2014_v90_01]
file=/data/glcf-nx-003/fengm/tcc/global/v05/water/2014/comp/list/wf_global_2014.shp
color=/data/glcf-st-004/data/workspace/fengm/etc/color/water_freq_color_solid_pub.txt

[water_freq_2015_v90_02]
file=/data/glcf-nx-003/fengm/tcc/global/v05/water/2015/comp_etm_oli/list/wat_freq_global_2015.shp
color=/data/glcf-st-004/data/workspace/fengm/etc/color/water_freq_color_solid_pub.txt

[water_freq_gb_2010_v10.1]
file=/data/glcf-nx-003/fengm/tcc/global/v05/water/2010/comp2/list/global_water_req_2010.shp
color=/data/glcf-st-004/data/workspace/fengm/etc/color/water_freq_color_solid_pub.txt

