
[general]

host=
port=8080

nodata_file=/data/glcf-st-004/data/workspace/fengm/local/etc/nodata.png
map_path=/data/glcf-st-004/data/workspace/fengm/serv/map
web_path=/data/glcf-st-004/data/workspace/fengm/serv/test
test_path=/data/glcf-st-004/data/workspace/fengm/serv/test
ndvi_path=/data/glcf-nx-002/data/PALSAR/modis/ndvi/bip2/list/ndvi_bip.txt
water_path=/data/glcf-st-004/data/workspace/fengm/data/modis_water/ext/modis_water_mod44w.shp

dmap=build_map_tile.py -t %[tag]s -l %[level]s -c %[col]s -r %[row]s

[conf]
log=/export2/data/mfeng/map_server.log

# aggregate=mean
# aggregate=dominated
# aggregate=dominated
aggregate=mean
# mmu=true
mmu=false

[percent-layer]
file=[shapefile path]
percent=[value]

[map layer]
file=[shapefile path]
color=[color path]

