
[conf]

host=
port=8080

ssl_key=
ssl_crt=

#'', gevent, eventlet
kernal=gevent

threaded=false
process=8

min_level=9

min_dtile_level=10
max_dtile_jobs=-1

timeout=60
graceful_timeout=60

output=

# aggregate=mean
# aggregate=dominated
# aggregate=dominated
aggregate=mean
# mmu=true
mmu=false

[general]

nodata_file=%(config_path)s/nodata.png

; map_path=%(root)s/map
map_path=s3://geo-map-tiles/tiles
; web_path=%(root)s/web
web_path=s3://geo-map-tiles/web

test_path=%(root)s/test

dmap=build_map_tile.py -t %[tag]s -l %[level]s -c %[col]s -r %[row]s

[percent-layer]
file=[shapefile path]
percent=[value]

[map layer]
file=[shapefile path]
color=[color path]

# [layer]
# [item]=[path]
#
# for example
#
# [layer1]
# loss=s3://geo-dataset/test1/list.shp
#

#
# define the mask files
[mask]
# for example:
# test1=/mnt/data1/mfeng/test/test1.tif
#

