
[conf]

host=
port=8080

ssl_key=
ssl_crt=

threaded=false
process=32

min_dtile_level=10
max_dtile_jobs=-1

timeout=60
graceful_timeout=60

output=

# aggregate=mean
# aggregate=dominated
# aggregate=dominated
aggregate=mean
# mmu=true
mmu=false

[general]

nodata_file=%(root)s/conf/nodata.png
map_path=%(root)s/map
web_path=%(root)s/web
test_path=%(root)s/test

dmap=build_map_tile.py -t %[tag]s -l %[level]s -c %[col]s -r %[row]s

[percent-layer]
file=[shapefile path]
percent=[value]

[map layer]
file=[shapefile path]
color=[color path]

