
[conf]

color=
# output=/mnt/data1/mfeng/var/map
# output=s3://geo-map-tiles/tiles
output=s3://geo-map-tiles-w2/tiles
cache_s3_image=false

openlayers_temp=%(root)s/conf/openlayers.html

[pgdb]
host=tpdb02.cluster-c3ctshmavtci.us-west-2.rds.amazonaws.com
port=1152
user=tpgis
dbname=tpgisdb
password=Tpg!$u$3r

# [pgdb_east_1]
# host=tpdb01.cluster-compweaqr5k6.us-east-1.rds.amazonaws.com
# user=tpgis
# port=5432
# dbname=tpgisdb
# password=Tpg!$u$3r