
[conf]

color=
; output=/mnt/data1/mfeng/var/map
output=s3://geo-map-tiles/tiles
cache_s3_image=false

openlayers_temp=%(root)s/conf/openlayers.html

[pgdb]
host=tpdb01.cluster-compweaqr5k6.us-east-1.rds.amazonaws.com
user=tpgis
dbname=tpgisdb
password=Tpg!$u$3r
