
[conf]

# input=/mnt/data1/mfeng/var/map
# input=s3://geo-map-tiles/tiles
input=s3://geo-map-tiles-w2/tiles
cache_s3_image=false

# aggregate=mean
# aggregate=dominated
# aggregate=dominated
aggregate=median
# mmu=true
mmu=false

[general]
nodata_file=%(config_path)s/nodata.png
